### ISSUE TITLE
How to deal with dependencies

### ISSUE THREAD

**Issue by D3vil0p3r** [Miosso/rust-workspace#1]
Considering the project structure of this repository, in case we would like to define and use dependencies as:
```toml
[dependencies]
clap = {version = "4.4.4", features = ["derive"] }
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
toml = "0.8.0"
log = "0.4.20"
flexi_logger = {version = "0.27.2", features = ["colors"] }
human-panic = "1.2.0"
regex = "1.9.5"
```
how they should be dealt?

I tried to insert them in `shared` with no luck. Not clear how they must be used in order to be found during the building.
